apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: logs-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: logs-dep
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50