apiVersion: apps/v1
kind: Deployment
metadata:
  name: logs-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logs
  template:
    metadata:
      labels:
        app: logs
    spec:
      volumes: # Define volume
        - name: outputs
          emptyDir: {}
      containers:
        - name: log-writer
          image: lapalmerjack/output-saver:latest
          ports:
            - containerPort: 8080 
          volumeMounts: # Mount volume
          - name: outputs
            mountPath: /app/storage
        - name: log-reader
          image: lapalmerjack/output-reader:latest
          ports:
            - containerPort: 8080 
          volumeMounts: # Mount volume
          - name: outputs
            mountPath: /app/storage